name: Playground
on:
  workflow_dispatch:
jobs:
  playground:
    name: Randomized tests
    runs-on: ubuntu-latest
    env:
      ci: ${{ CI }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.8'
      - name: Get commit sha
        id: vars
        shell: bash
        run: |
          echo "CI: ${{ env.ci }}"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: 1
          body: |
            Sha: [${{ steps.vars.outputs.sha_short }}](${{ github.server_url }}/${{ github.repository }}/tree/${{ steps.vars.outputs.sha_short }})
