name: Wiki publish

on:
  push:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Full url to repository.'
        required: false
        default: https://github.com/Qiskit/qiskit-finance

jobs:
  generate_issue_report:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d_%H:%M')"
      - name: Check vars
        run: printenv | sed 's;=.*;;' | sort
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Pick branch
        run: git config init.defaultBranch main
      - name: Generate wiki file
        run: |
          mkdir reports
          cd reports
          echo "# WIKI page ${{ steps.date.outputs.date }}" >> wiki_page_1_${{ steps.date.outputs.date }}.md
      - name: Upload Report to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "reports"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
